# Generated by Django 5.1.7 on 2025-03-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langGraph', '0003_graphstate_delete_chatmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('checkpoint_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('thread_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField()),
            ],
            options={
                'db_table': 'checkpoints',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='GraphState',
        ),
    ]
