# Generated by Django 5.1.6 on 2025-02-28 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parrafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=255, verbose_name='Nombre')),
                ('metadatos', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.proyecto')),
            ],
            options={
                'verbose_name': 'Párrafo',
                'verbose_name_plural': 'Párrafos',
            },
        ),
    ]
