# Generated by Django 5.1.6 on 2025-02-28 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parrafo',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parrafos', to='main.proyecto'),
        ),
        migrations.AlterField(
            model_name='parrafo',
            name='texto',
            field=models.TextField(verbose_name='Texto'),
        ),
    ]
