# Generated by Django 5.1.6 on 2025-02-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedding',
            name='archivo',
            field=models.FileField(upload_to='embeddings/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='embedding',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='embedding',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='embedding',
            name='procesado',
            field=models.BooleanField(default=False, verbose_name='Procesado'),
        ),
    ]
