# Generated by Django 5.1.7 on 2025-04-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_rag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='messages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='state',
            name='summary',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='state',
            name='token_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.JSONField(default=dict),
        ),
    ]
