# Generated by Django 5.1.7 on 2025-04-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_rag', '0002_state_messages_state_summary_state_token_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='state',
        ),
    ]
