# Generated by Django 5.1.7 on 2025-04-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_rag', '0003_remove_state_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='summary',
            field=models.JSONField(default=str),
        ),
    ]
